<?php

namespace Paco\Bundle\FollowableBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowableEntityRepository extends EntityRepository
{

}
